services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vialibre
      MONGO_INITDB_ROOT_PASSWORD: vialibre
      MONGO_INITDB_DATABASE: vialibre
    networks:
      - vialibre

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vialibre
      ME_CONFIG_MONGODB_ADMINPASSWORD: vialibre
      ME_CONFIG_MONGODB_URL: mongodb://vialibre:vialibre@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - vialibre

networks:
  vialibre:
    name: vialibre-network